---
title: "STEM Data Analysis"
output: html_notebook
---

```{r}
stem_org = read.csv("stem.csv")

# subset out original dataset
stem = stem_org[1:866,]
```

```{r}
# ordinal pooling, questions Q3.1 to Q3.24
barplot(table(stem$Q3.1))
table(stem$Q3.2)

reordered = as.data.frame(sapply(stem, function(x) as.integer(factor(as.character(x), levels=c("Strongly Disagree","Disagree","Not Sure", "Agree", "Strongly Agree")))))

stem[24:47] = reordered[24:47]
```

```{r}
# make a copy incase we need original rows for later analysis
stem_ordinal = stem[24:47]
stem_ordinal = na.omit(stem_ordinal)

# possible rule: if you combine 2 ends and they do not take up at least 20% of the data, then combine 3 closest
# if combining 3 closest takes up over 50% then stop

#### Q3.1 ####

# checking
barplot(table(stem_ordinal$Q3.1))
cat("Total of all levels:", sum(table(stem_ordinal$Q3.1)), "\n")
cat("Total of levels 1-3:", sum(table(stem_ordinal$Q3.1)[1:3]))

# changing levels
stem_ordinal$Q3.1[stem_ordinal$Q3.1 == 1 | stem_ordinal$Q3.1 == 2 | stem_ordinal$Q3.1 == 3 ] <- 1
stem_ordinal$Q3.1[stem_ordinal$Q3.1 == 4] <- 2
stem_ordinal$Q3.1[stem_ordinal$Q3.1 == 5] <- 3

# checking after 
barplot(table(stem_ordinal$Q3.1)) # good
```

